//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "directories")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub path: String,
    pub parent_id: Option<i64>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "parent_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub directories: HasOne<Entity>,
    #[sea_orm(has_many)]
    pub files: HasMany<super::files::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
