//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "files")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "uq_files_directory_id_name_extension")]
    pub directory_id: i64,
    #[sea_orm(unique_key = "uq_files_directory_id_name_extension")]
    pub name: String,
    #[sea_orm(unique_key = "uq_files_directory_id_name_extension")]
    pub extension: String,
    pub hash: String,
    pub hash_algorithm: String,
    pub size_bytes: i64,
    pub created_at: DateTimeWithTimeZone,
    pub modified_at: DateTimeWithTimeZone,
    pub missing_since: Option<DateTimeWithTimeZone>,
    #[sea_orm(has_many)]
    pub audio_streams: HasMany<super::audio_streams::Entity>,
    #[sea_orm(
        belongs_to,
        from = "directory_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub directories: HasOne<super::directories::Entity>,
    #[sea_orm(has_one)]
    pub media_files: HasOne<super::media_files::Entity>,
    #[sea_orm(has_one)]
    pub subtitle_files: HasOne<super::subtitle_files::Entity>,
    #[sea_orm(has_many)]
    pub subtitle_streams: HasMany<super::subtitle_streams::Entity>,
    #[sea_orm(has_many)]
    pub video_streams: HasMany<super::video_streams::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
