//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "languages")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub iso_639_1: Option<String>,
    pub iso_639_2: Option<String>,
    pub name: Option<String>,
    #[sea_orm(has_many)]
    pub audio_streams: HasMany<super::audio_streams::Entity>,
    #[sea_orm(has_many)]
    pub subtitle_streams: HasMany<super::subtitle_streams::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
