//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "subtitle_files")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub file_id: i64,
    pub media_file_id: i64,
    #[sea_orm(
        belongs_to,
        from = "file_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub files: HasOne<super::files::Entity>,
    #[sea_orm(
        belongs_to,
        from = "media_file_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub media_files: HasOne<super::media_files::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
