//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "subtitle_streams")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "uq_subtitle_streams_file_id_stream_index")]
    pub file_id: i64,
    #[sea_orm(unique_key = "uq_subtitle_streams_file_id_stream_index")]
    pub stream_index: i64,
    pub title: Option<String>,
    pub codec: String,
    pub language_id: Option<i64>,
    pub is_default: bool,
    pub is_forced: bool,
    pub is_sdh: bool,
    #[sea_orm(
        belongs_to,
        from = "file_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub files: HasOne<super::files::Entity>,
    #[sea_orm(
        belongs_to,
        from = "language_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub languages: HasOne<super::languages::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
