//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "video_streams")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique_key = "uq_video_streams_file_id_stream_index")]
    pub file_id: i64,
    #[sea_orm(unique_key = "uq_video_streams_file_id_stream_index")]
    pub stream_index: i64,
    pub codec: String,
    pub width: i64,
    pub height: i64,
    pub bit_depth: Option<i64>,
    pub hdr_format: Option<String>,
    pub bitrate: Option<i64>,
    #[sea_orm(
        belongs_to,
        from = "file_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub files: HasOne<super::files::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
